[package]
name = "vslpub"
description = "VideoStream ROS Publisher"
repository = "https://bitbucket.org/au-zone/vslpub"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = {version = "1.12.0", features = ["attributes"] }
clap = { version = "4.4.6", features = ["derive"] }
zenoh = "0.10.0-rc"
zenoh-ros-type = { git = "https://github.com/evshary/zenoh-ros-type", branch = "main" }
serde = "1.0.147"
serde_derive = "1.0.147"
cdr = "0.2.4"
videostream = "0.5.2"
vaal = "0.3.0"
deepviewrt = "0.4.0"